# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  builder: html

python:
   version: 3.7
   install:
      - requirements: doc_requirements.txt

formats:
  - epub
  - pdf

