branches:
  only:
    - master
    - /rc\/.+/
    - /feature\/.+/

env:
  global:
    - TEST_NWB_FILES=skip
    - TEST_OBSERVATORY_EXPERIMENT_PLOTS_DATA=skip
    - TEST_API_ENDPOINT=http://api.brain-map.org 
    - TEST_COMPLETE=false
    - TEST_BAMBOO=false
    - LIMS_DBNAME=db
    - LIMS_PORT=1234
    - LIMS_PASSWORD=password
    - LIMS_HOST=host
    - LIMS_USER=user
    - MTRAIN_DBNAME=db
    - MTRAIN_USER=user
    - MTRAIN_HOST=host
    - MTRAIN_PORT=1234
    - MTRAIN_PASSWORD=password

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.6
      env: TEST_PYTHON_VERSION=3.6
    - os: linux
      sudo: required
      python: 3.7
      env: TEST_PYTHON_VERSION=3.7.3
    - os: osx
      language: generic
      env: TEST_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env: TEST_PYTHON_VERSION=3.7

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      brew update;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$TEST_PYTHON_VERSION pip
  - source activate test-environment
  - pip install codecov
  - pip install -r test_requirements.txt
  - pip install .

script:
  - py.test --cov=allensdk -n 4 --durations=0
  - codecov
