
# http://gembundler.com/gemfile.html
#
# after updating a gem, you might want to run
# bundle update gemname
# bundle install
#
source 'http://rubygems.org'
source 'http://gems'

gem 'active_scaffold'
#gem 'active_scaffold_export', :path => 'vendor/gems/active_scaffold_export-3.3.0'
gem 'active_scaffold_batch'
gem 'active_scaffold_sortable', '3.2.10'
gem 'recordselect', '3.2.6' # TODO: there is a bug in the most recent record select -- Investigate because new recordselect is cool!
#gem 'rails', '3.2.18' # TODO: upgrade to latest rails.
gem 'rails', '3.2.15' # TODO: downgrade for now since there are bugs.

gem 'pg'
gem "strip_attributes"

# for lab tracks connection
gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter'

gem 'acts_as_reportable'
gem 'acts_as_list'
gem 'ruport'
gem 'aasm', :require => 'aasm'

gem 'rmagick'
gem 'exifr'
gem 'ruby-ole'
gem 'spreadsheet'
gem 'ruby-graphviz', :require => 'graphviz'
gem 'therubyracer'
gem 'roo', '1.11.2' # TODO: need to keep at this version until Jose investigates
gem 'rubyzip', '< 1.0.0' # TODO: need to keep at this version until Jose investigates

gem 'siv_engine', '>=0.0.87'

gem 'nokogiri'
gem 'bunny', '1.7.1'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails'
  gem 'uglifier'
end

gem 'sass-rails'

gem 'builder'
gem 'polyglot'
gem 'bio'
gem 'net-ldap'
gem 'audited-activerecord', :require => 'audited-activerecord'
gem 'acts_as_tree'
gem 'active_scaffold_config_list'


gem 'prototype-rails'

#active scaffold currently needs this version of jquery
gem 'jquery-rails', '2.1.4' #TODO: need to keep this here because of bugs in later versions. -ajs, chrisb
gem 'jquery-ui-rails'

gem 'dynamic_form' #add in some of the removed form func from rails 2

# RMA
gem 'service_adapter_engine', '~> 0.40.8'
gem 'rma_engine', '= 0.40.4.rc10'
gem 'acts_as_rdf_engine', '~> 0.40.0'
gem 'antlr3', '1.8.12'
gem 'rdf', '1.99.1'
gem 'json-ld', '1.0.7'

# House gems
gem 'delivery-path-message'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem 'newrelic_rpm'
  gem 'database_cleaner'
  gem 'rubocop', require: false
  gem 'simplecov'
  gem 'test-unit'
  gem 'mocha'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'factory_girl', '4.2.0' # TODO: Factories need to be changed to support new syntax
  gem 'factory_girl_rails', '4.2.1' # TODO: Factories need to be changed to support new syntax
  gem 'ci_reporter_test_unit'
  gem 'thin'
  gem 'ruby-prof'
  gem 'bumbler'
  gem 'spring'
  gem 'rails-dev-tweaks'
  gem 'curb'
  gem 'table_print'
  gem 'flog'
  gem 'reek', '2.2.1'
end

