FROM tensorflow/tensorflow:1.13.2-gpu

RUN apt-get update && apt-get install -y \
	wget \
	vim \
	python-wxtools \
	xvfb \
	curl \
	unzip \
	ffmpeg \
	git \
	bzip2

#Install MINICONDA
RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O Miniconda.sh && \
	/bin/bash Miniconda.sh -b -p /opt/conda && \
	rm Miniconda.sh
ENV PATH /opt/conda/bin:$PATH

#Install ANACONDA Environment
RUN conda create -y -n dlc python=3.6 imageio=2.3.0 numpy=1.14.5 six=1.11.0 wxPython anaconda && \
	/opt/conda/envs/dlc/bin/pip install tensorflow-gpu deeplabcut==2.0.7.2 google-cloud-storage

# Setup working dir:
RUN mkdir -p /workdir
WORKDIR /workdir

# Add trained model:
ARG MODELFILE
COPY ${MODELFILE} .
RUN mkdir -p /workdir/model
RUN unzip ${MODELFILE} -d ./tmp
RUN mv ${MODELFILE} tmp/*/* model

# Add dlc-eye-tracking code:
COPY DLC_Labeled_Video.py .

# For debugging:
CMD ["/bin/bash", "-c", "source activate dlc && python DLC_Labeled_Video.py --video_input_file=$VIDEO_INPUT_FILE"]
