FROM tensorflow/tensorflow:1.13.2-gpu

RUN apt-get update && apt-get install -y \
	wget \
	vim \
	python-wxtools \
	xvfb \
	curl \
	unzip \
	ffmpeg \
	git \
	bzip2

#Install MINICONDA
RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O Miniconda.sh && \
	/bin/bash Miniconda.sh -b -p /opt/conda && \
	rm Miniconda.sh
ENV PATH /opt/conda/bin:$PATH

#Install ANACONDA Environment
RUN conda create -y -n dlc python=3.6 imageio=2.3.0 numpy=1.14.5 six=1.11.0 wxPython anaconda && \
	/opt/conda/envs/dlc/bin/pip install google-cloud-storage deeplabcut==2.0.7.2

# Setup working dir:
RUN mkdir -p /workdir
WORKDIR /workdir

# Add ellipses dependency:
RUN git clone https://github.com/AllenInstitute/least-squares-ellipse-fitting.git
ENV PYTHONPATH="$PYTHONPATH:/workdir/least-squares-ellipse-fitting"

# Add dlc-eye-tracking code:
COPY DLC_Ellipse_Fitting.py .

# For debugging:
# COPY 770233648_410314_20181030.eye.avi ./video_input_file.api
CMD ["/bin/bash", "-c", "source activate dlc && python DLC_Ellipse_Fitting.py --video_input_file=770233648_410314_20181030.eye.avi"]

# Entrypoint
# CMD ["/bin/bash", "-c", "source activate dlc && python $SCRIPT $ARGS"]
