version: "2"
services:
  db:
    restart: on-failure:3
    image: "postgres:9.4.2"
    stdin_open: true
    tty: true
    volumes:
        - pgdata:/var/lib/postgresql/data/pgdata
    ports: 
        - "5432:5432"
    environment:
        - POSTGRES_DB=lims2docker
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - PGDATA=/var/lib/postgresql/data/pgdata
  lims:
    image: alleninstitute/lims_base:centos7
    environment:
        - RAILS_ENV=development
        - VERBOSE=true
        - INCLUDE_CACHED=false
        - PGPASSFILE='/home/docker/.pgpass
    command: bash --login /home/docker/lims/rake_test_loader
    stdin_open: true
    tty: true
    ports: 
        - "3000:3000"
    depends_on:
        - db
    volumes:
        - ./lims:/home/docker/lims
        - ./tmp:/tmp
        - /data:/data
volumes:
    pgdata:
        external: true
